### PR TITLE
display agencies using dependent products

### PR DESCRIPTION
**Pull request by dsiddy**
I modified `StorageData.products()` to find the `Data` object corresponding to each dependent product and add its agencies to the list.

My associated test ensures that `/product/datapipe-government-solutions-federal-community-cloud-platform` lists the National Science Foundation, as desired.

### CODE REVIEW

**Comment by dsiddy** [comment]
This pull request addresses #52, referenced by [this 18F Micro-purchase auction](https://micropurchase.18f.gov/auctions/33).

**Comment by dsiddy** [comment]
`s/dependent/underlying/g` in my commit messages.

**Comment by dsiddy** [comment]
Also, it appears that Office 365 Multi-Tenant & Supporting Services has three underlying packages of its own. This should bring the prescribed count for the National Science Foundation to 8 instead of 5, correct?

**Comment by lauraGgit** [comment]
Yes, we are looking to make sure that all of the underlying packages are listed for every product at every agency.

**Comment by mgwalker** [comment]
Evaluating.  Will update this comment as I go.
- [x] Update the Product Page
- [x] Update the Agency Page
- [x] Update the "Number of Products Used" for Agencies
- [x] Does not degrade code climate rating
  - **Note:** Code Climate isn't setup to check PRs.  However, eyeballing the code, it looks good to me.  If Code Climate has any complaints, I suspect they would be quite minor.
- [x] Covered by new unit tests
- [x] No decrease in test coverage
  - **Note:** Coverage reporting prior to the PR does not appear to be setup correctly with coveralls.io, so I compared using LCOV output from the `npm test` command.  Coverage increased.
- [x] Tests run on Travis-CI and do not break the build
- [x] Does not degrade accessibility

**Comment by lauraGgit** [comment]
FYSA, the coveralls.io problem came from the transfer of the repo from the original vendor to `18F`. Several tickets have been created with Coveralls to try to correctly change the source.

**Comment by mgwalker** [comment]
This PR doesn't seem to cover recursive dependencies.  E.g., if an agency uses the **CloudService** package and the **CloudService** package has **Office365** as an underlying package, **Office365**'s underlying packages aren't displayed on the agency page (unless **CloudService** just happens to include those in its own underlying packages).

**Comment by mgwalker** [comment]
Talked to @lauraGgit and we think the _data_ accounts for these recursive relationships, so it should not be necessary for the code to do it.  In that case, looks good to me!

:rocket: :shipit:

**Comment by dsiddy** [comment]
Funny you should mention that, @mgwalker. Truth be told, I had the same concern.

**Pull request merged**
